services:
  app:
    build:
      context: .
    container_name: devops-mini-con
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    volumes:
      - devops-mini-volume:/app/data
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: devops-mini-mongo
    restart: unless-stopped
    env_file:
      - mongo.env
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    

volumes:
  devops-mini-volume:
  mongodb-data:
  mongodb-config:
  