name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug GitHub event
        run: |
          echo "EVENT=${{ github.event_name }}"
          echo "REF=${{ github.ref }}"
          echo "SHA=${{ github.sha }}"
          echo "REPOSITORY=${{ github.repository }}"

      - name: Get GitHub OIDC token
        if: github.event_name == 'push'
        uses: actions/github-script@v8
        id: oidc
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');

            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            );

            console.log(JSON.stringify({
              iss: payload.iss,
              aud: payload.aud,
              sub: payload.sub,
              repository: payload.repository,
              ref: payload.ref
            }, null, 2));

      - name: Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::980819806634:role/devops-mini-github-actions-role
          aws-region: eu-north-1

      - name: Check AWS Identity
        if: github.event_name == 'push'
        run: |
          aws sts get-caller-identity

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: |
          echo "IMAGE=${REGISTRY}/${IMAGE_NAME,,}" >> "$GITHUB_ENV"

      - name: Show image name
        run: |
          echo "IMAGE=$IMAGE"

      - name: Build image
        run: |
          docker build \
            -t "$IMAGE:${GITHUB_SHA}" \
            -t "$IMAGE:latest" \
            ./app

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push "$IMAGE:${GITHUB_SHA}"
          docker push "$IMAGE:latest"

      - name: Run container
        run: |
          docker run -d \
            --name devops-mini-api \
            -p 3000:3000 \
            "$IMAGE:${GITHUB_SHA}"

      - name: Health check
        run: |
          sleep 2
          curl --fail http://localhost:3000/health

      - name: Show logs
        if: failure()
        run: |
          docker logs devops-mini-api